#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-keytool
Version  : 1.5
Release  : 1
URL      : https://github.com/mojohaus/keytool/archive/keytool-1.5.tar.gz
Source0  : https://github.com/mojohaus/keytool/archive/keytool-1.5.tar.gz
Source1  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar
Source2  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.pom
Source3  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar
Source4  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.pom
Source5  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
Source6  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.pom
Source7  : https://repo1.maven.org/maven2/org/codehaus/mojo/keytool/1.5/keytool-1.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-keytool-data = %{version}-%{release}
Requires: mvn-keytool-license = %{version}-%{release}

%description
Creating a keystore file.
If validity is out, use the following cli to regenerate a keystore, certificate-request and certificate

%package data
Summary: data components for the mvn-keytool package.
Group: Data

%description data
data components for the mvn-keytool package.


%package license
Summary: license components for the mvn-keytool package.
Group: Default

%description license
license components for the mvn-keytool package.


%prep
%setup -q -n keytool-keytool-1.5

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-keytool
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/LICENSE.txt
cp keytool-api-1.5/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/keytool-api-1.5_LICENSE.txt
cp keytool-api-1.6/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/keytool-api-1.6_LICENSE.txt
cp keytool-api-1.7/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/keytool-api-1.7_LICENSE.txt
cp keytool-api/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/keytool-api_LICENSE.txt
cp keytool-maven-plugin/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-keytool/keytool-maven-plugin_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool/1.5
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/keytool/1.5/keytool-1.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/keytool/1.5/keytool-1.5.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-keytool/LICENSE.txt
/usr/share/package-licenses/mvn-keytool/keytool-api-1.5_LICENSE.txt
/usr/share/package-licenses/mvn-keytool/keytool-api-1.6_LICENSE.txt
/usr/share/package-licenses/mvn-keytool/keytool-api-1.7_LICENSE.txt
/usr/share/package-licenses/mvn-keytool/keytool-api_LICENSE.txt
/usr/share/package-licenses/mvn-keytool/keytool-maven-plugin_LICENSE.txt
